version: '2'
services:
  action:
    build: .
    env_file: secrets.env
    command: |-
      '{
        "channel": "#my-channel",
        "text": ":docker: `image` was built successfully *TESTING*",
        "blocks": [
          {
            "type": "section",
            "text": { "type": "mrkdwn",  "text": ":docker: `image` was built successfully *TESTING*" }
          }
        ]
      }'